[package]
name = "elements2"
version = "0.1.0"
authors = ["Bluemi <bruno.schilling@protonmail.ch>", "memoryleak47 <memoryleak47@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml = "0.15"
itertools = "0.9"
num-traits = "0.2"
rand = "0.7"
rand_xorshift = "0.2"
gilrs = "0.7.2"
bitflags = "1.2.1"

[profile.release]
debug = true
