version: "3.3"

services:
  elements-master-server:
    image: "bruno1996/elements2-server"
    environment:
      RUST_BACKTRACE: full
      ELEMENTS_IDENTITY_PASSPHRASE: $ELEMENTS_IDENTITY_PASSPHRASE
    volumes:
      - .:/root
    restart: "always"
    network_mode: "host"
    container_name: "elements-master-server"
    working_dir: "/root"
    command: "/root/target/release/elements-master-server --identity-file /root/identity.pfx"
