version: "3.3"

services:
  elements-master-server:
    image: "archlinux:latest"
    environment:
      RUST_BACKTRACE: full
    volumes:
      - .:/root
    restart: "always"
    network_mode: "host"
    container_name: "elements-master-server"
    working_dir: "/root"
    command: "/root/target/release/elements-master-server --identity-file /root/identity.pfx"
