version: "3.3"

services:
  elements-game-server-0:
    image: "bruno1996/elements2-server"
    volumes:
      - .:/root
    environment:
      RUST_BACKTRACE: full
      ELEMENTS_IDENTITY_PASSPHRASE: $ELEMENTS_IDENTITY_PASSPHRASE
    restart: "always"
    network_mode: "host"
    container_name: "elements-game-server-0"
    working_dir: "/root"
    command: "/root/target/release/elements-game-server --port 7575 --domain-name generic-sauce.de --identity-file /root/identity.pfx"
  elements-game-server-1:
    image: "bruno1996/elements2-server"
    volumes:
      - .:/root
    environment:
      RUST_BACKTRACE: full
      ELEMENTS_IDENTITY_PASSPHRASE: $ELEMENTS_IDENTITY_PASSPHRASE
    restart: "always"
    network_mode: "host"
    container_name: "elements-game-server-1"
    working_dir: "/root"
    command: "/root/target/release/elements-game-server --port 7577 --domain-name generic-sauce.de --identity-file /root/identity.pfx"
  elements-game-server-2:
    image: "bruno1996/elements2-server"
    volumes:
      - .:/root
    environment:
      RUST_BACKTRACE: full
      ELEMENTS_IDENTITY_PASSPHRASE: $ELEMENTS_IDENTITY_PASSPHRASE
    restart: "always"
    network_mode: "host"
    container_name: "elements-game-server-2"
    working_dir: "/root"
    command: "/root/target/release/elements-game-server --port 7579 --domain-name generic-sauce.de --identity-file /root/identity.pfx"
